export default {
  NunitoBlack: require("./Nunito-Black.ttf"),
  NunitoBlackItalic: require("./Nunito-BlackItalic.ttf"),
  NunitoBold: require("./Nunito-Bold.ttf"),
  NunitoBoldItalic: require("./Nunito-BoldItalic.ttf"),
  NunitoExtraBold: require("./Nunito-ExtraBold.ttf"),
  NunitoExtraBoldItalic: require("./Nunito-ExtraBoldItalic.ttf"),
  NunitoExtraLight: require("./Nunito-ExtraLight.ttf"),
  NunitoExtraLightItalic: require("./Nunito-ExtraLightItalic.ttf"),
  NunitoItalic: require("./Nunito-Italic.ttf"),
  NunitoLight: require("./Nunito-Light.ttf"),
  NunitoLightItalic: require("./Nunito-LightItalic.ttf"),
  Nunito: require("./Nunito-Regular.ttf"),
  NunitoSemiBold: require("./Nunito-SemiBold.ttf"),
  NunitoSemiBoldItalic: require("./Nunito-SemiBoldItalic.ttf"),
};
